[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
aiogram = "^3.10.0"
email-validator = "^2.2.0"


[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
